spring.application.name=tareas-api


# Fíjate que ponemos jdbc:postgresql:// + EL NUEVO HOST + : + EL NUEVO PUERTO + /postgres
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres

# El usuario que te marque ahora (si es postgres solo, pues postgres)
spring.datasource.username=postgres.hlsvxuaqlivoeihfggko

# Tu contraseña real (SIN CORCHETES, ponla tal cual)
spring.datasource.password=vkyLDWJhls1l3mz

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
